scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['planka-node-exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['planka-cadvisor:8080']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
